export const sixLetterWordSet = [
    "abroad", "absorb", "accent", "access", "across", "acting", "action", 
    "active", "actual", "advice", "advise", "affect", "afford", "agency", 
    "agenda", "almost", "always", "amount", "animal", "annual", "answer", 
    "anyone", "appear", "around", "arrive", "artist", "aspect", "assess", 
    "assist", "assume", "attack", "attend", "august", "author", "avenue", 
    "backed", "bakery", "barely", "battle", "beauty", "became", "become", 
    "before", "behalf", "behind", "belief", "belong", "better", "beyond", 
    "bishop", "border", "bottle", "bottom", "bought", "branch", "breath", 
    "bridge", "bright", "broken", "budget", "burden", "bureau", "button", 
    "camera", "cancer", "cannot", "carbon", "career", "castle", "casual", 
    "caught", "center", "chance", "change", "charge", "choice", "choose", 
    "church", "circle", "client", "closed", "closer", "coffee", "column", 
    "combat", "comedy", "comfort", "coming", "common", "comply", "copper", 
    "corner", "costly", "county", "couple", "course", "covers", "create", 
    "credit", "crisis", "custom", "damage", "danger", "dealer", "debate", 
    "decade", "decide", "defend", "define", "degree", "demand", "depend", 
    "deputy", "desert", "design", "desire", "detail", "detect", "device", 
    "differ", "dinner", "direct", "doctor", "dollar", "domain", "double", 
    "driven", "driver", "during", "easily", "eating", "editor", "effect", 
    "effort", "eighth", "either", "eleven", "emerge", "empire", "employ", 
    "enable", "ending", "energy", "engage", "engine", "enough", "ensure", 
    "entire", "entity", "equity", "escape", "estate", "ethics", "ethnic", 
    "exceed", "except", "excess", "expand", "expect", "expert", "export", 
    "extend", "extent", "fabric", "facing", "factor", "failed", "fairly", 
    "fallen", "family", "famous", "farmer", "faster", "father", "favour", 
    "female", "figure", "filing", "finger", "finish", "fiscal", "flight", 
    "flying", "follow", "forced", "forest", "forget", "formal", "format", 
    "former", "foster", "fought", "fourth", "friend", "future", "garden", 
    "gather", "gender", "genius", "gentle", "gently", "genuine", "giggle", 
    "global", "golden", "ground", "growth", "guilty", "handed", "handle", 
    "happen", "hardly", "headed", "health", "height", "hidden", "holder", 
    "honest", "impact", "import", "income", "indeed", "injury", "inside", 
    "intend", "intent", "invest", "island", "itself", "jacket", "jersey", 
    "joined", "joint", "journey", "joyful", "judge", "jungle", "junior", 
    "latter", "launch", "lawyer", "leader", "league", "leaves", "legacy", 
    "length", "lesson", "letter", "lights", "likely", "linked", "liquid", 
    "listen", "little", "living", "losing", "lucent", "luxury", "mainly", 
    "making", "manage", "manner", "manual", "margin", "marine", "marked", 
    "market", "marvel", "massive", "master", "matter", "medium", "member", 
    "memory", "mental", "merely", "method", "middle", "minute", "mirror", 
    "mobile", "modern", "modest", "module", "moment", "morale", "mostly", 
    "mother", "motion", "moving", "murder", "museum", "mutual", "myself", 
    "narrow", "nation", "native", "nature", "nearby", "nearly", "nights", 
    "nobody", "normal", "notice", "notion", "number", "object", "obtain", 
    "office", "offset", "online"
]

export const sevenLetterWordSet = [
    "account", "achieve", "acquire", "address", "advance", "adviser", "against", 
    "airline", "airport", "alcohol", "alleged", "already", "analyst", 
    "ancient", "another", "anxiety", "anxious", "anybody", "applied", 
    "arrange", "arrival", "article", "artisan", "athlete", "attempt", 
    "attract", "auction", "average", "backing", "balance", "banking", 
    "barrier", "battery", "bearing", "beating", "bedroom", "believe", 
    "benefit", "besides", "between", "billion", "binding", "brother", 
    "cabinet", "caliber", "calling", "capable", "capital", "captain", 
    "caption", "capture", "careful", "carrier", "caution", "ceiling", 
    "central", "century", "certain", "chamber", "channel", "chapter", 
    "charity", "charter", "checked", "chicken", "circuit", "classes", 
    "classic", "climate", "closing", "closure", "clothes", "collect", 
    "college", "combine", "comfort", "command", "comment", "compact", 
    "company", "compare", "compete", "complex", "concept", "concern", 
    "concert", "conduct", "confirm", "connect", "consent", "consider", 
    "consist", "contact", "contain", "content", "contest", "context", 
    "control", "convert", "correct", "council", "counsel", "counter", 
    "country", "couple", "courage", "covered", "creator", "cricket", 
    "culture", "current", "cutting", "decades", "declare", "decline", 
    "default", "defeat", "defence", "deficit", "deliver", "density", 
    "deposit", "desktop", "despite", "destroy", "develop", "devoted", 
    "diamond", "digital", "discuss", "disease", "display", "dispute", 
    "distant", "diverse", "divided", "drawing", "driving", "dynamic", 
    "economy", "edition", "elderly", "element", "engaged", "enhance", 
    "essence", "evening", "evident", "exactly", "examine", "example", 
    "excited", "exclude", "exhibit", "expense", "explain", "explore", 
    "express", "extreme", "factory", "faculty", "failing", "failure", 
    "fashion", "feature", "federal", "feeling", "fiction", "fifteen", 
    "filling", "finance", "finding", "fishing", "fitness", "foreign", 
    "forever", "formula", "fortune", "forward", "founder", "freedom", 
    "further", "gallery", "gateway", "general", "genetic", "genuine", 
    "gesture", "getting", "hanging", "heading", "healthy", "hearing", 
    "heavily", "helpful", "helping", "herself", "highway", "himself", 
    "history", "holding", "holiday", "housing", "however", "hundred", 
    "husband", "illegal", "illness", "imagine", "imaging", "improve", 
    "include", "initial", "inquiry", "insight", "install", "instant", 
    "instead", "intense", "interim", "involve", "jointly", "journal", 
    "journey", "justice", "justify", "keeping", "killing", "kingdom", 
    "kitchen", "knowing", "landing", "largely", "lasting", "leading", 
    "learned", "leisure", "liberal", "liberty", "library", "license", 
    "limited", "listing", "logical", "loyalty", "machine", "manager", 
    "married", "massive", "maximum", "meaning", "measure", "medical", 
    "meeting", "mention", "message", "million", "mineral", "minimal", 
    "minimum", "missing", "mission", "mistake", "mixing", "monitor", 
    "monthly", "morning", "musical", "mystery", "natural", "neither", 
    "nervous", "network", "neutral", "notable", "nothing", "nowhere", 
    "nuclear", "nursing", "obvious", "offense", "officer", "ongoing", 
    "opening", "operate", "opinion", "optical", "organic", "outcome", 
    "outdoor", "outlook", "outside", "overall", "packing", "package", 
    "painted", "parking", "partial", "partner", "passage", "passing", 
    "passion", "passive", "patient", "pattern", "paying", "penalty", 
    "pending", "pension", "percent", "perfect", "perform", "perhaps", 
    "period", "permit", "persist", "personal", "phase", "phenomen", 
    "physical", "picking", "picture", "pioneer", "planned", "plastic", 
    "pointed", "popular", "portion", "poverty", "precise", "predict", 
    "premier", "premium", "prepare", "present", "prevent", "primary", 
    "prince", "printer", "privacy", "private", "problem", "proceed", 
    "process", "produce", "product", "profile", "program", "project", 
    "promise", "promote", "prompt", "proper", "prospect", "protect", 
    "protein", "protest", "provide", "public", "publish", "purpose", 
    "pushing", "putting", "quality", "quarter", "question", "quickly", 
    "quietly", "radical", "raising", "random", "rapidly", "rarely", 
    "reached", "react", "reading", "reality", "realize", "really", 
    "reason", "receipt", "receive", "recent", "recess", "recipe", 
    "record", "recover", "reflect", "reform", "refuge", "refuse", 
    "regard", "regime", "region", "regular", "related", "relax", 
    "release", "relief", "rely", "remain", "remark", "remedy", 
    "remember", "remind", "remote", "remove", "repair", "repeat", 
    "replace", "report", "request", "require", "reserve", "resolve", 
    "resort", "respect", "respond", "restore", "result", "retain", 
    "retire", "return", "reveal", "revenue", "reverse", "review", 
    "revise", "rhythm", "richly", "rightly", "risking", "routine", 
    "running", "sadly", "safety", "salary", "sample", "saving", 
    "saying", "scheme", "school", "science", "score", "scratch", 
    "screen", "script", "search", "season", "second", "secret", 
    "section", "sector", "secure", "seeing", "select", "selling", 
    "send", "senior", "sense", "series", "serious", "service", 
    "session", "setting", "settle", "several", "severe", "sexual", 
    "shadow", "sharply", "shelter", "shift", "shocked", "shortly", 
    "showing", "shrink", "silent", "similar", "simple", "simply", 
    "singing", "single", "sister", "sitting", "situation", "skill", 
    "slight", "slowly", "small", "smooth", "social", "softly", 
    "solely", "solicit", "solid", "solution", "somehow", "someone", 
    "something", "sometime", "somewhat", "soon", "sorry", "sorted", 
    "sound", "source", "space", "spare", "speaking", "special", 
    "specific", "speech", "speed", "spend", "spent", "spirit", 
    "spoken", "spread", "spring", "square", "stable", "staff", 
    "stage", "stand", "standard", "start", "state", "station", 
    "statute", "stay", "steady", "steal", "steel", "steep", 
    "steer", "step", "stick", "still", "stir", "stock", "stolen", 
    "stop", "store", "storm", "story", "straight", "strange", 
    "strategic", "strength", "stress", "stretch", "strict", 
    "strike", "string", "strong", "struggle", "study", "stuff", 
    "style", "subject", "submit", "substance"
]